# Configuration for PBIP parameter automation
# This file defines how CSV columns map to parameters in the model.bim file

parameters:
  # String parameters
  - name: "Name"           # Must match parameter name in model.bim
    type: "string"         # Data type for validation and conversion
  
  - name: "Owner"
    type: "string"
  
  # Numeric parameters (if you add them to your model.bim)
  # - name: "Budget"
  #   type: "float"
  
  # - name: "Year"
  #   type: "integer"
  
  # Boolean parameters (if you add them to your model.bim)
  # - name: "IsActive"
  #   type: "boolean"

output:
  # Naming pattern for generated folders
  # Use any CSV column names in curly braces
  naming_pattern: "{Name}_{Owner}"
  directory: "./output"

logging:
  level: "INFO"           # Logging level: DEBUG, INFO, WARNING, ERROR
  format: "json"          # Log format: json, text
  file: "pbi_automation.log"  # Optional log file 