# Configuration for PBIP parameter automation
# This file defines how CSV columns map to parameters in the semantic model

parameters:
  # String parameters
  - name: "Name"           # Must match parameter name in semantic model
    type: "string"         # Data type for validation and conversion
  
  - name: "Owner"
    type: "string"
  
  # Numeric parameters (if you add them to your semantic model)
  # - name: "Budget"
  #   type: "float"
  
  # - name: "Year"
  #   type: "integer"
  
  # Boolean parameters (if you add them to your semantic model)
  # - name: "IsActive"
  #   type: "boolean"

output:
  directory: "./output"

logging:
  level: "INFO"           # Logging level: DEBUG, INFO, WARNING, ERROR
  format: "json"          # Log format: json, text
  file: "pbi_automation.log"  # Optional log file 